[build-system]
requires = [
    "setuptools",
    "wheel",
]
build-backend = "setuptools.build_meta"

[project]
name = "wexample-filestate-git"
version = "0.0.23"
description = "An extension for \"filestate\" package, which adds GIT management operations."
authors = [
    { name = "weeger", email = "contact@wexample.com" },
]
requires-python = ">=3.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "pip-tools",
    "pydantic",
    "pytest",
    "requests",
    "wexample-filestate==0.0.31",
    "wexample-helpers-git==0.0.31",
    "wexample-helpers==0.0.31",
    "wexample-prompt==0.0.32",
]

[project.readme]
file = "README.md"
content-type = "text/markdown"

[project.license]
text = "MIT"

[project.urls]
homepage = "https://github.com/wexample/python-filestate-git"
